### ISSUE TITLE
Repo search page doesn't show pagination

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/opensource.microsoft.com#44]
On this page: https://opensource.microsoft.com/projects/explore/

I do not see any page controls or the ability to have infinite scrolling. Also, the filter by language doesn't seem to work for me.

Using Edge 84 (Stable channel) on macOS.

**Comment by jeffwilcox** [comment]
Thanks! Confirming the pagination controls and features were cut for launch so there's more work to be done there.

On the filtering, this is a known issue that will be fixed in https://github.com/microsoft/opensource.microsoft.com/issues/36

I'll keep this issue open to represent the pagination or infinite scrolling feature, closing once it ships.

**Comment by jeffwilcox** [comment]
Closing; unfortunately we're not actively working in this space, and can revisit this backlog later.
